name: CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Fetch Sources
        uses: actions/checkout@v4
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.1.0
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-home-cache-cleanup: true
      - name: Build plugin
        run: ./gradlew buildPlugin

  test:
    name: Test
    needs: [ build ]
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - ide_type: 'IU'
            ide_version: '2022.2.5'
            py_version: '222.4554.10'
            go_version: '222.4459.24'
          - ide_type: 'IU'
            ide_version: '2023.3.7'
            py_version: '233.11799.196'
            go_version: '233.11799.196'
          - ide_type: 'IU'
            ide_version: '2024.1'
            py_version: '241.14494.127'
            go_version: '241.14494.127'
    steps:

      - name: Fetch Sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-home-cache-cleanup: true
      - name: Set IDE Name and Version
        run: |
          echo "INTELLIJ_TYPE=${{ matrix.ide_type }}" >> $GITHUB_ENV
          echo "INTELLIJ_VERSION=${{ matrix.ide_version }}" >> $GITHUB_ENV
          echo "PY_VERSION=${{ matrix.py_version }}" >> $GITHUB_ENV
          echo "GO_VERSION=${{ matrix.go_version }}" >> $GITHUB_ENV
      - name: Run Tests
        run: ./gradlew buildPlugin verifyPlugin check
      - name: Collect Tests Result
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: tests-result
          path: ${{ github.workspace }}/build/reports/tests
      - name: Upload Code Coverage Report
        uses: codecov/codecov-action@v3
        with:
          files: ${{ github.workspace }}/build/reports/kover/report.xml